### ISSUE TITLE
How do i use this in real live automation test

### ISSUE THREAD

**Issue by lummyare** [JaniJegoroff/android-adb-extension#2]
Thanks for the link please how to i use this gem in a scenario where i have a calabash-android framework set with gemfile etc. 
And i want to run few of my scenarios for the app to start without airplay active or no internet access.

Expected result is meant to be: 
The web app should show an offline page for user.

I will really appreciate your prompt response.

Thanks

**Comment by JaniJegoroff** [comment]
Have you checked the `Readme`? There are installation instructions and example use cases that will help you to get started.

**Comment by JaniJegoroff** [comment]
Closing since all needed information provided in Readme.
