### ISSUE TITLE
reverse landscape is not recognised in v 0.0.9

### ISSUE THREAD

**Issue by RamaSky** [JaniJegoroff/android-adb-extension#5]
device set to reverse landscape, but is not recognised as landscape, here is the output from ruby console

irb(main):017:0> ADB.landscape?
true
irb(main):018:0> ADB.orientation
1
irb(main):019:0> ADB.portrait?
true
irb(main):020:0> ADB.orientation
0
**irb(main):021:0> ADB.landscape?
false
irb(main):022:0> ADB.orientation
3**
irb(main):023:0> ADB.portrait?
true
irb(main):024:0> ADB.orientation
2

**Comment by JaniJegoroff** [comment]
Could you give a try for latest version 0.1.1?

**Comment by RamaSky** [comment]
This is fixed in version 0.1.1, thanks a lot for the quick fix

irb(main):005:0> ADB.orientation
1
irb(main):006:0> ADB.landscape?
true
irb(main):007:0> ADB.orientation
3
irb(main):008:0> ADB.landscape?
true
